tld = "example.com"
hostname = "www.example.com"
email = "tech@example.com"

[AWS]
instanceType = "t3.micro"
instanceID = "i-0123456789abcdef0"
prodIP = "127.0.0.1"
publicIP = "127.0.0.1"

[Django]
project = "myapp"
mainApp = "myapp"
modelVizApps = ""

[DB]
dbhost = "localhost"
dbUser = "django"
dbName = "django"
dbPassword = "foo"
sqlite = true
sqliteFile = "django.db"
