[configuration]
long_hostname=Example server
threshold=75
devices=/dev/xvda1

[email]
hostname=smtp.example.com
username=service
sender=service@example.com
receivers=support@example.com
password=secret
port=587
tls=True
